version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/postgresData:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U Misfio32"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
      POSTGRES_USER: "Misfio32"
      POSTGRES_PASSWORD: "Smena"
      POSTGRES_DB: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    networks:
      - bench
