# Используем официальный образ Node.js
FROM node:18-alpine AS builder

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем package.json и package-lock.json
COPY ../web/package.json ../web/package-lock.json ./

# Устанавливаем зависимости
RUN npm install --omit=dev

# Копируем остальные файлы проекта
COPY ../web/ .

# Запускаем фронтенд
CMD ["npm", "start"]
